apiVersion: v1
kind: Secret
metadata:
  name: game-secrets
  namespace: la-hucha-de-paredes
type: Opaque
stringData:
  mongodb_uri: "mongodb://username:password@mongodb:27017/hucha-de-paredes?authSource=admin"
  jwt_secret: "your-jwt-secret-key-here"
  admin_password: "your-admin-password-here"
  redis_password: "your-redis-password-here"
  webrtc_ice_servers: |
    [
      {"urls": "stun:stun.l.google.com:19302"},
      {"urls": "stun:stun1.l.google.com:19302"},
      {
        "urls": "turn:turn.example.com:3478",
        "username": "turnuser",
        "credential": "turnpassword"
      }
    ]
